name: CI

on:
  push:
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '.gitignore'
      - 'roles/backup/**'
      - 'roles/restore/**'
      - 'roles/settings/**'
      - 'roles/nvidia/**'
      - 'roles/plex_extra_tasks/**'
      - 'roles/plex_auth_token/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '.gitignore'
      - 'roles/backup/**'
      - 'roles/restore/**'
      - 'roles/settings/**'
      - 'roles/nvidia/**'
      - 'roles/plex_extra_tasks/**'
      - 'roles/plex_auth_token/**'
  workflow_dispatch:

jobs:
  install:
    name: '${{ matrix.roles }}'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        roles:
          - saltbox
          - feederbox
          - mediabox
          - media-server
          - tautulli
          - overseerr
          - portainer
          - organizr
          - cloudplow
          - nzbget
          - rutorrent
          - jackett
          - nzbhydra2
          - sonarr
          - radarr
          - lidarr
          - iperf3
          - nethogs
          - glances
          - btop
          - asshama
          - autoheal
          - autoscan
          - bazarr
          - btrfsmaintenance
          - ddclient
          - deluge
          - emby
          - jellyfin
          - netdata
          - nginx
          - nzbthrottle
          - petio
          - plex
          - plex_autoscan
          - prowlarr
          - qbittorrent
          - readarr
          - sabnzbd
          - sstv
          - subliminal
          - trackarr
          - traktarr
          - transfer
          - yyq
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: curl https://raw.githubusercontent.com/grayplex/Ansible-Deployment/main/Scripts/dep.sh --output dep.sh && sudo bash dep.sh -v
        
      - name: Create /srv/git
        run: sudo mkdir /srv/git

      - name: Symlink cloned repository to /srv/git/Ansible-Deployment
        run: sudo ln -s $GITHUB_WORKSPACE /srv/git/Ansible-Deployment

      - name: Chown /srv/git
        run: sudo chown -R runner:runner /srv/git

      - name: Import default configuration
        run: for i in defaults/*; do cp -n $i "$(basename "${i%.*}")"; done

      - name: Edit accounts.yml
        run: sed -i 's/seed/runner/g' accounts.yml

      - name: Run Tree
        run: tree -a

      - name: Syntax Check
        run: sudo ansible-playbook grayplex.yml --syntax-check

      - name: Install Grayplex Core
        run: sudo ansible-playbook grayplex.yml --tags "core" --skip-tags "settings" --extra-vars '{"continuous_integration":true}'

      - name: Install Grayplex ${{ matrix.roles }}
        run: sudo ansible-playbook grayplex.yml --tags "${{ matrix.roles }}" --skip-tags "settings,plex-extra-tasks,core" --extra-vars '{"continuous_integration":true}'

  webhook:
    name: 'webhook'
    runs-on: ubuntu-20.04
    needs: install
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ env.WORKFLOW_CONCLUSION }}
